# Generated by Django 3.1.4 on 2021-03-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bankdetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('bankName', models.CharField(max_length=90)),
                ('ifscCode', models.CharField(max_length=50)),
                ('accountNumber', models.IntegerField()),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='customerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('aadharNo', models.IntegerField()),
                ('address', models.CharField(max_length=90)),
                ('business', models.CharField(max_length=90)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=90)),
                ('transactionNo', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('interest', models.IntegerField(default=0)),
                ('interestAmount', models.IntegerField(default=0)),
                ('Amountfinal', models.IntegerField(default=0)),
                ('paidAmount', models.IntegerField(default=0)),
                ('chequeNumber', models.IntegerField(default=0)),
                ('Udays', models.IntegerField(default=0)),
                ('todayDate', models.DateTimeField(default=0)),
                ('expectedDay', models.DateTimeField()),
                ('morgage', models.CharField(max_length=90)),
                ('guaranteePerson', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='partnerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('initialAmount', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='signupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=90)),
                ('lastName', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateTimeField()),
                ('gender', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=90)),
            ],
        ),
    ]
