# Generated by Django 3.1.4 on 2021-03-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20210308_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmodel',
            name='chequeNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loanmodel',
            name='guaranteePerson',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='loanmodel',
            name='morgage',
            field=models.CharField(default='', max_length=90),
        ),
    ]
