# Generated by Django 3.1.4 on 2021-03-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_loanmodel_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmodel',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
