# Generated by Django 3.1.4 on 2021-04-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20210309_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmodel',
            name='iscompleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loanmodel',
            name='chequeNumber',
            field=models.IntegerField(default='', null=True),
        ),
    ]
