# Generated by Django 3.1.4 on 2021-04-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_customermodel_isapprove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmodel',
            name='chequeNumber',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
