# Generated by Django 3.1.4 on 2021-04-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_auto_20210414_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmodel',
            name='chequeNumber',
            field=models.IntegerField(null=True),
        ),
    ]
