# Generated by Django 3.1.4 on 2021-04-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_auto_20210414_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmodel',
            name='chequeNumber',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
