# Generated by Django 3.1.4 on 2021-04-23 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_transactionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='paidDate',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
