# Generated by Django 3.1.4 on 2021-04-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_transactionmodel_paiddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmodel',
            name='iscompleted',
            field=models.BooleanField(default=False),
        ),
    ]
