# Generated by Django 3.2 on 2021-05-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_auto_20210427_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='transactionID',
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
