# Generated by Django 3.2 on 2021-05-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_auto_20210501_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='transactionID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
