# Generated by Django 3.2 on 2021-05-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_auto_20210501_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='transactionID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
