# Generated by Django 3.2 on 2021-05-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_alter_transactionmodel_transactionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='transactionID',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
