# Generated by Django 3.2 on 2021-05-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_alter_transactionmodel_transactionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='transactionID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
