# Generated by Django 3.2 on 2021-05-06 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_alter_signupmodel_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='transactionID',
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 0, 51, 30, 623775)),
        ),
    ]
