# Generated by Django 3.2 on 2021-05-11 18:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_auto_20210509_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetailmodel',
            name='profileId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='finance.signupmodel'),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 0, 1, 31, 683554)),
        ),
    ]
