# Generated by Django 3.2 on 2021-05-11 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_auto_20210512_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 0, 7, 59, 66993)),
        ),
    ]
