# Generated by Django 3.2 on 2021-05-14 17:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0034_auto_20210512_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmodel',
            name='customerName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.customermodel'),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 23, 28, 6, 633602)),
        ),
    ]
