# Generated by Django 3.2 on 2021-05-21 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0037_alter_signupmodel_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='initialCapital',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 21, 11, 41, 11, 894166)),
        ),
    ]
